site_name: Unity-Powershell Documentation
repo_url: https://github.com/equelin/Unity-Powershell
site_author: Erwan Quelin
theme: readthedocs
copyright: "Unity-Powershell is licensed under the <a href='https://github.com/equelin/Unity-Powershell/blob/master/LICENSE'>MIT license</a>"
pages:
  - Home: index.md
  - Introduction:
    - Prerequisites: prerequisites.md
    - Installation: installation.md
    - Getting Started: gettingstarted.md
  - FAQ: FAQ.md
  - Functions References:
    - Connect-Unity: References/Connect-Unity.md
    - Disable-UnityFastCache: References/Disable-UnityFastCache.md
    - Disconnect-Unity: References/Disconnect-Unity.md
    - Enable-UnityFastCache: References/Enable-UnityFastCache.md
    - Get-UnityAlert: References/Get-UnityAlert.md
    - Get-UnityAlertConfig: References/Get-UnityAlertConfig.md
    - Get-UnityBasicSystemInfo: References/Get-UnityBasicSystemInfo.md
    - Get-UnityBattery: References/Get-UnityBattery.md
    - Get-UnityCIFSServer: References/Get-UnityCIFSServer.md
    - Get-UnityCIFSShare: References/Get-UnityCIFSShare.md
    - Get-UnityDae: References/Get-UnityDae.md
    - Get-UnityDataCollectionResult: References/Get-UnityDataCollectionResult.md
    - Get-UnityDatastore: References/Get-UnityDatastore.md
    - Get-UnityDisk: References/Get-UnityDisk.md
    - Get-UnityDiskGroup: References/Get-UnityDiskGroup.md
    - Get-UnityDNSServer: References/Get-UnityDNSServer.md
    - Get-UnityDpe: References/Get-UnityDpe.md
    - Get-UnityEncryption: References/Get-UnityEncryption.md
    - Get-UnityESXi: References/Get-UnityESXi.md
    - Get-UnityEthernetPort: References/Get-UnityEthernetPort.md
    - Get-UnityFastCache: References/Get-UnityFastCache.md
    - Get-UnityFastVP: References/Get-UnityFastVP.md
    -  Get-UnityFCPort: References/ Get-UnityFCPort.md
    - Get-UnityFeature: References/Get-UnityFeature.md
    - Get-UnityFileDNSServer: References/Get-UnityFileDNSServer.md
    - Get-UnityFileInterface: References/Get-UnityFileInterface.md
    - Get-UnityFilesystem: References/Get-UnityFilesystem.md
    - Get-UnityHost: References/Get-UnityHost.md
    - Get-UnityHostInitiator: References/Get-UnityHostInitiator.md
    - Get-UnityHostIPPort: References/Get-UnityHostIPPort.md
    - Get-UnityInstalledSoftwareVersion: References/Get-UnityInstalledSoftwareVersion.md
    - Get-UnityIpInterface: References/Get-UnityIpInterface.md
    - Get-UnityIPPort: References/Get-UnityIPPort.md
    - Get-UnityIscsiPortal: References/Get-UnityIscsiPortal.md
    - Get-UnityItem: References/Get-UnityItem.md
    - Get-Unityjob: References/Get-Unityjob.md
    - Get-UnityLicense: References/Get-UnityLicense.md
    - Get-UnityLinkAggregation: References/Get-UnityLinkAggregation.md
    - Get-UnityLUN: References/Get-UnityLUN.md
    - Get-UnityMetric: References/Get-UnityMetric.md
    - Get-UnityMetricQueryResult: References/Get-UnityMetricQueryResult.md
    - Get-UnityMetricRealTimeQuery: References/Get-UnityMetricRealTimeQuery.md
    - Get-UnityMetricValue: References/Get-UnityMetricValue.md
    - Get-UnityMgmtInterface: References/Get-UnityMgmtInterface.md
    - Get-UnityMgmtInterfaceSetting: References/Get-UnityMgmtInterfaceSetting.md
    - Get-UnityNASServer: References/Get-UnityNASServer.md
    - Get-UnityNFSServer: References/Get-UnityNFSServer.md
    - Get-UnityNFSShare: References/Get-UnityNFSShare.md
    - Get-UnityNTPServer: References/Get-UnityNTPServer.md
    - Get-UnityPool: References/Get-UnityPool.md
    - Get-UnityPoolUnit: References/Get-UnityPoolUnit.md
    -  Get-UnityServiceAction: References/ Get-UnityServiceAction.md
    - Get-UnityServiceInfo: References/Get-UnityServiceInfo.md
    - Get-UnitySession: References/Get-UnitySession.md
    - Get-UnitySMTPServer: References/Get-UnitySMTPServer.md
    - Get-UnitySnap: References/Get-UnitySnap.md
    - Get-UnitySnapSchedule: References/Get-UnitySnapSchedule.md
    - Get-UnitySsc: References/Get-UnitySsc.md
    - Get-UnitySsd: References/Get-UnitySsd.md
    - Get-UnityStorageProcessor: References/Get-UnityStorageProcessor.md
    - Get-UnityStorageResource: References/Get-UnityStorageResource.md
    - Get-UnitySystem: References/Get-UnitySystem.md
    - Get-UnityUser: References/Get-UnityUser.md
    - Get-UnityvCenter: References/Get-UnityvCenter.md
    - Get-UnityVM: References/Get-UnityVM.md
    - Get-UnityVMwareLUN: References/Get-UnityVMwareLUN.md
    - Get-UnityVMwareNasPEServer: References/Get-UnityVMwareNasPEServer.md
    - Get-UnityVMwareNFS: References/Get-UnityVMwareNFS.md
    - Get-UnityVMwarePE: References/Get-UnityVMwarePE.md
    - Get-UnityX509Certificate: References/Get-UnityX509Certificate.md
    - New-UnityCIFSServer: References/New-UnityCIFSServer.md
    - New-UnityCIFSShare: References/New-UnityCIFSShare.md
    - New-UnityFileDNSServer: References/New-UnityFileDNSServer.md
    - New-UnityFileInterface: References/New-UnityFileInterface.md
    - New-UnityFilesystem: References/New-UnityFilesystem.md
    - New-UnityHost: References/New-UnityHost.md
    - New-UnityHostIPPort: References/New-UnityHostIPPort.md
    - New-UnityiSCSIPortal: References/New-UnityiSCSIPortal.md
    - New-UnityLUN: References/New-UnityLUN.md
    - New-UnityMetricRealTimeQuery: References/New-UnityMetricRealTimeQuery.md
    - New-UnityMgmtInterface: References/New-UnityMgmtInterface.md
    - New-UnityNASServer: References/New-UnityNASServer.md
    - New-UnityNFSServer: References/New-UnityNFSServer.md
    - New-UnityNFSShare: References/New-UnityNFSShare.md
    - New-UnityPool: References/New-UnityPool.md
    - New-UnitySMTPServer: References/New-UnitySMTPServer.md
    - New-UnitySnap: References/New-UnitySnap.md
    - New-UnitySnapSchedule: References/New-UnitySnapSchedule.md
    - New-UnityUser: References/New-UnityUser.md
    - New-UnityvCenter: References/New-UnityvCenter.md
    - New-UnityVMwareLUN: References/New-UnityVMwareLUN.md
    - New-UnityVMwareNFS: References/New-UnityVMwareNFS.md
    - Remove-UnityAlert: References/Remove-UnityAlert.md
    - Remove-UnityCIFSServer: References/Remove-UnityCIFSServer.md
    - Remove-UnityCIFSShare: References/Remove-UnityCIFSShare.md
    - Remove-UnityFileDNSServer: References/Remove-UnityFileDNSServer.md
    - Remove-UnityFileInterface: References/Remove-UnityFileInterface.md
    - Remove-UnityFilesystem: References/Remove-UnityFilesystem.md
    - Remove-UnityHost: References/Remove-UnityHost.md
    - Remove-UnityHostIPPort: References/Remove-UnityHostIPPort.md
    - Remove-UnityiSCSIPortal: References/Remove-UnityiSCSIPortal.md
    - Remove-UnityLUN: References/Remove-UnityLUN.md
    - Remove-UnityMgmtInterface: References/Remove-UnityMgmtInterface.md
    - Remove-UnityNASServer: References/Remove-UnityNASServer.md
    - Remove-UnityNFSServer: References/Remove-UnityNFSServer.md
    - Remove-UnityNFSShare: References/Remove-UnityNFSShare.md
    - Remove-UnityPool: References/Remove-UnityPool.md
    - Remove-UnitySMTPServer: References/Remove-UnitySMTPServer.md
    - Remove-UnitySnap: References/Remove-UnitySnap.md
    - Remove-UnitySnapSchedule: References/Remove-UnitySnapSchedule.md
    - Remove-UnityUser: References/Remove-UnityUser.md
    - Remove-UnityvCenter: References/Remove-UnityvCenter.md
    - Remove-UnityVMwareLUN: References/Remove-UnityVMwareLUN.md
    - Remove-UnityVMwareNFS: References/Remove-UnityVMwareNFS.md
    - Set-UnityAlert: References/Set-UnityAlert.md
    - Set-UnityAlertConfig: References/Set-UnityAlertConfig.md
    - Set-UnityCIFSShare: References/Set-UnityCIFSShare.md
    - Set-UnityDNSServer: References/Set-UnityDNSServer.md
    - Set-UnityFileDnsServer: References/Set-UnityFileDnsServer.md
    - Set-UnityFileInterface: References/Set-UnityFileInterface.md
    - Set-UnityFilesystem: References/Set-UnityFilesystem.md
    - Set-UnityHost: References/Set-UnityHost.md
    - Set-UnityHostIPPort: References/Set-UnityHostIPPort.md
    - Set-UnityIscsiPortal: References/Set-UnityIscsiPortal.md
    - Set-UnityLUN: References/Set-UnityLUN.md
    - Set-UnityMgmtInterface: References/Set-UnityMgmtInterface.md
    - Set-UnityMgmtInterfaceSetting: References/Set-UnityMgmtInterfaceSetting.md
    - Set-UnityNASServer: References/Set-UnityNASServer.md
    - Set-UnityNFSServer: References/Set-UnityNFSServer.md
    - Set-UnityNFSShare: References/Set-UnityNFSShare.md
    - Set-UnityNTPServer: References/Set-UnityNTPServer.md
    - Set-UnityPool: References/Set-UnityPool.md
    - Set-UnityserviceAction: References/Set-UnityserviceAction.md
    - Set-UnitySMTPServer: References/Set-UnitySMTPServer.md
    - Set-UnitySnap: References/Set-UnitySnap.md
    - Set-UnitySnapSchedule: References/Set-UnitySnapSchedule.md
    - Set-UnitySystem: References/Set-UnitySystem.md
    - Set-UnityUser: References/Set-UnityUser.md
    - Set-UnityvCenter: References/Set-UnityvCenter.md
    - Set-UnityVMwareLUN: References/Set-UnityVMwareLUN.md
    - Set-UnityVMwareNFS: References/Set-UnityVMwareNFS.md
    - Test-UnityEmailAlert: References/Test-UnityEmailAlert.md
    - Test-UnityUCAlert: References/Test-UnityUCAlert.md
    - Test-UnityUIAlert: References/Test-UnityUIAlert.md
    - Update-UnityvCenter: References/Update-UnityvCenter.md

